version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: ls -l && go build -o out/pkcalc && ls -l && ls -l out
      - store_artifacts:
           path: out/pkcalc

